[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
db = { path = "../db" }
service = { path = "../service" }
axum = "0.7.5"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
tracing-subscriber = "0.3.18"
